import burger from '../Images/burger.jpg'
import kadhai_paneer from '../Images/kadhai_paneer.jpg'


const data=[
    {
        id:1,
        name:'A.D Brothers',
        image: burger,
        is_available:true,
        forMany:'150 for 2',
        type:'Veg',
        rating:4,
        address:'Gomati Nagar',
        offer:'25% Off on this Merchant.',
        deliveryDuration:'Deliver in 25 Mints',
        categoryId:1,
    },
    {
        id:2,
        name:'Step In Cafe',
        image: kadhai_paneer,
        is_available:true,
        forMany:'200 for 1',
        type:'Non Veg',
        rating:5,
        address:'Indra Nagar',
        offer:'19% Off on this Merchant.',
        deliveryDuration:'Deliver in 9 Mints',
        categoryId:2,
    },
    {
        id:3,
        name:'Spicy Hub',
        image: burger,
        is_available:true,
        forMany:'150 for 2',
        type:'Veg',
        rating:4,
        address:'Gomati Nagar',
        offer:'25% Off on this Merchant.',
        deliveryDuration:'Deliver in 25 Mints',
        categoryId:1,
    },
    {
        id:4,
        name:'Kohinoor Biryani',
        image: kadhai_paneer,
        is_available:true,
        forMany:'200 for 1',
        type:'Non Veg',
        rating:5,
        address:'Indra Nagar',
        offer:'19% Off on this Merchant.',
        deliveryDuration:'Deliver in 9 Mints',
        categoryId:2,
    },
    {
        id:5,
        name:'Famous Dum',
        image: burger,
        is_available:true,
        forMany:'150 for 2',
        type:'Veg & Non Veg Both',
        rating:4,
        address:'Gomati Nagar',
        offer:'25% Off on this Merchant.',
        deliveryDuration:'Deliver in 25 Mints',
        categoryId:1,
    },
    {
        id:6,
        name:'Rolls Villa',
        image: kadhai_paneer,
        is_available:true,
        forMany:'200 for 1',
        type:'Non Veg',
        rating:5,
        address:'Indra Nagar',
        offer:'19% Off on this Merchant.',
        deliveryDuration:'Deliver in 9 Mints',
        categoryId:2,
    },
    {
        id:7,
        name:'Dhadhoom Pizza',
        image: burger,
        is_available:true,
        forMany:'150 for 2',
        type:'Veg',
        rating:4,
        address:'Gomati Nagar',
        offer:'25% Off on this Merchant.',
        deliveryDuration:'Deliver in 25 Mints',
        categoryId:1,
    },
    {
        id:8,
        name:'Tandon Bakery',
        image: kadhai_paneer,
        is_available:true,
        forMany:'200 for 1',
        type:'Non Veg',
        rating:5,
        address:'Indra Nagar',
        offer:'19% Off on this Merchant.',
        deliveryDuration:'Deliver in 9 Mints',
        categoryId:2,
    },
    {
        id:9,
        name:'Pizza Cave',
        image: burger,
        is_available:true,
        forMany:'150 for 2',
        type:'Veg',
        rating:4,
        address:'Gomati Nagar',
        offer:'25% Off on this Merchant.',
        deliveryDuration:'Deliver in 25 Mints',
        categoryId:1,
    },
    {
        id:10,
        name:'Hot Rolls',
        image: kadhai_paneer,
        is_available:true,
        forMany:'200 for 1',
        type:'Non Veg',
        rating:5,
        address:'Indra Nagar',
        offer:'19% Off on this Merchant.',
        deliveryDuration:'Deliver in 9 Mints',
        categoryId:2,
    },
]


export default data